### ISSUE TITLE
Running benchmarks

### ISSUE THREAD

**Issue by andsanmar** [OleksiiOleksenko/SpecFuzz#13] opened 2020-07-29 11:19 UTC
Hello, I achieved to run the benchmarks os `usesec20` for `http` and `jsmn`, but for the rest of benchmarks, `SRC` has no content in the respective Makefile. Maybe I've missed it, but what should I use for that benchmarks?

**Comment by OleksiiOleksenko** [comment] 2020-07-30 08:34
For each benchmark, the process is:
1. Pull the benchmark's repository. Links are in the [README](https://github.com/OleksiiOleksenko/SpecFuzz/blob/master/example/usesec20/README.md). Don't forget to checkout the correct version!
2. Copy all the files from the corresponding subdirectory of `example/usesec20`.
3. Follow the steps in the corresponding `experiment.md` file

**Comment by andsanmar** [comment] 2020-07-30 10:42
Yes, I followed the same procedure for `http`, `brotli` and `jsmn`, but when executing `make sf SF_COLLECT=1` in any of the other repositories (with the Makefile provided), it fails because SRC is not specified (as asserted in `common.mk:2`)

**Comment by canertol** [comment] 2020-10-08 16:33
> Yes, I followed the same procedure for `http`, `brotli` and `jsmn`, but when executing `make sf SF_COLLECT=1` in any of the other repositories (with the Makefile provided), it fails because SRC is not specified (as asserted in `common.mk:2`)

When I try to build according to the 'example/usesec20/openssl/experiment.md' it gives me the following error:

```
 /bin/sh: 2: ./config: not found
 Makefile:33: recipe for target 'sf' failed
```

Similarly, for libyaml,

```
/bin/sh: 2: ./configure: not found
Makefile:27: recipe for target 'sf' failed
```
I couldn't find the _config_ or _configure_ files. Are they missing or do have to specify a different LIB_DIR?

Thanks.

**Comment by OleksiiOleksenko** [comment] 2020-10-09 09:29
Did you download the sources of OpenSSL and libYAML? The the `config` files are there.

**Comment by andsanmar** [comment] 2020-10-12 07:30
I suggest to use git submodules, is going to make easier to know the concrete version of the repository to fuzz and a single command will let the user to get the desired sources

**Comment by canertol** [comment] 2020-10-14 21:26
@OleksiiOleksenko 
> Did you download the sources of OpenSSL and libYAML? The the `config` files are there.

The Makefile is overwritten when I try to build inside the source folder. I have tried with openssl-3.0.0-alpha1 and openssl-3.0.0-alpha6.
```
~/tmp/openssl$ make sf SF_COLLECT=1
../common.mk:2: warning: SRC is not specified (ignore this warning if the benchmark overwrites the build targets.)
Makefile:19: warning: overriding recipe for target 'native'
../common.mk:24: warning: ignoring old recipe for target 'native'
Makefile:26: warning: overriding recipe for target 'nativecov'
../common.mk:37: warning: ignoring old recipe for target 'nativecov'
Makefile:33: warning: overriding recipe for target 'sf'
../common.mk:53: warning: ignoring old recipe for target 'sf'
Makefile:40: warning: overriding recipe for target 'slh'
../common.mk:67: warning: ignoring old recipe for target 'slh'
Makefile:47: warning: overriding recipe for target 'patched'
../common.mk:83: warning: ignoring old recipe for target 'patched'
cd ./ && \
	./config no-asm no-shared no-threads no-fips no-legacy no-tests enable-fuzz-afl enable-tls1_3 enable-weak-ssl-ciphers enable-rc5 enable-md2 enable-ssl3 enable-ssl3-method enable-nextprotoneg \
	CC=/usr/bin/clang-sf CXX=/usr/bin/clang-sf++ CFLAGS="-O3 -ggdb -Wno-mismatched-tags --collect /home/caner/tmp/openssl/function_list.txt" CXXFLAGS="-O3 -ggdb -Wno-mismatched-tags --collect /home/caner/tmp/openssl/function_list.txt" LDFLAGS="-O3 -ggdb --collect /home/caner/tmp/openssl/function_list.txt -L/honggfuzz/installation/directory/src//libhfuzz/ -L/honggfuzz/installation/directory/src//libhfcommon -lhfuzz -lhfcommon"
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 3.0.0-alpha1 for target linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Running configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
make run_build
make[1]: Entering directory '/home/caner/tmp/openssl'
make[1]: *** No rule to make target 'run_build'.  Stop.
make[1]: Leaving directory '/home/caner/tmp/openssl'
Makefile:33: recipe for target 'sf' failed
make: *** [sf] Error 2

```

**Comment by OleksiiOleksenko** [comment] 2020-10-15 08:39
I see. Could you try the same, but put this Makefile in some other folder (outside the OpenSSL source tree) + change the `LIB_DIR` variable to point to the OpenSSL sources?

**Comment by canertol** [comment] 2020-10-16 04:51
> I see. Could you try the same, but put this Makefile in some other folder (outside the OpenSSL source tree) + change the `LIB_DIR` variable to point to the OpenSSL sources?

It works until it gives the following error. I tried installing `afl` but it didn't work.

```
fuzz/asn1-bin-driver.o: In function `main':
/home/caner/tmp/openssl/fuzz/driver.c:39: undefined reference to `__AFL_LOOP'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:5382: recipe for target 'fuzz/asn1' failed
make[3]: *** [fuzz/asn1] Error 1
make[3]: *** Waiting for unfinished jobs....
fuzz/asn1parse-bin-driver.o: In function `main':
/home/caner/tmp/openssl/fuzz/driver.c:39: undefined reference to `__AFL_LOOP'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:5393: recipe for target 'fuzz/asn1parse' failed
make[3]: *** [fuzz/asn1parse] Error 1
make[3]: Leaving directory '/home/caner/tmp/openssl'
Makefile:1329: recipe for target 'build_sw' failed
make[2]: *** [build_sw] Error 2
make[2]: Leaving directory '/home/caner/tmp/openssl'
Makefile:54: recipe for target 'run_build' failed
make[1]: *** [run_build] Error 2
make[1]: Leaving directory '/home/caner/tmp/SpecFuzz/example/usesec20/openssl'
Makefile:33: recipe for target 'sf' failed
make: *** [sf] Error 2

```

**Comment by OleksiiOleksenko** [comment] 2020-10-16 08:44
In `experiments/usesec20/openssl` there is a file `fuzz/driver.c`. Replace `fuzz/driver.c` within the openssl source code directory with this file.

**Comment by canertol** [comment] 2020-10-19 15:48
- When I run the following command

`honggfuzz  --run_time 3600 --exit_upon_crash -Q --no_fb_timeout 1 --timeout 120 -n 1 -f openssl-corpus/ -l hongg.log -- ./sf ___FILE___ 2>&1 | analyzer collect -r hongg.log -o analyzer.json -b sf >errors.log 2>&1`

I find the following log in the `hongg.log` file.

```
cmdline:'./sf ___FILE___', bin:'./sf' inputDir:'openssl-corpus/', fuzzStdin:false, mutationsPerRun:6, externalCommand:'', timeout:120, mutationsMax:0, threadsMax:1
.
.
.
[2020-10-16T17:11:46-0400][W][16640] input_init():188 open('openssl-corpus/', O_DIRECTORY|O_RDONLY|O_CLOEXEC): No such file or directory
[2020-10-16T17:11:46-0400][F][16640] main():259 Couldn't load input corpus

```

- I changed `openssl-corpus` as the path of the source code directory and run again. I think it works now.
Thanks a lot.

PS: I've also changed 
`analyzer aggregate minimal.json -s $(llvm-7.0.1-config --sfdir)/llvm-symbolizer -b ./sf -o aggregated.json` 
to
 `analyzer aggregate minimal.json -s llvm-symbolizer-3.6 -b ./sf -o aggregated.json`

**Comment by OleksiiOleksenko** [comment] 2020-10-20 09:02
You should replace `openssl-corpus` with a directory that includes your input corpora. You could use the corpora supplied with openssl (`fuzz/corpora/server`) or you could just create an empty directory. Pointing it to your source code doesn't make much sense.

**Comment by canertol** [comment] 2020-10-22 15:50
Thank you very much for the detailed answers. I have a few more questions.
`aggregated.json` gives the following result.
```
{
  "branches": {
    "/home/caner/tmp/openssl/fuzz/driver.c:37:0": {
      "location": "/home/caner/tmp/openssl/fuzz/driver.c:37:0",
      "branches": [
        {
          "address": "0x59110b",
          "faults": [],
          "fault_count": 64,
          "nonspeculative_execution_count": 64
        },
        {
          "address": "0x590ff1",
          "faults": [],
          "fault_count": 0,
          "nonspeculative_execution_count": 64
        }
      ],
      "symbolized_faults": [],
      "fault_counts": [
        64,
        0
      ],
      "nonspeculative_execution_counts": [
        64,
        64
      ]
    }, ......
```
Can you explain what exactly "address", "faults" and "fault_count" mean? The address locations give memory accessing instructions. Sometimes "faults":[] but fault_count is not 0.

Also, 
```analyzer query aggregated.json -o whitelist.txt``` 
gives me an empty whitelist for openssl meaning that none of the conditional jumps are safe. Is that normal?

**Comment by OleksiiOleksenko** [comment] 2020-12-26 16:14
> Can you explain what exactly "address", "faults" and "fault_count" mean? 

"address" is the address of this branch in the instrumented binary.
"faults" - a list of speculative memory violations caused by a misprediction of this branch
"fault_count" - how many unique inputs triggered this speculative memory violation

> Sometimes "faults":[] but fault_count is not 0.

It's not normal. It's either a bug or a misconfiguration. Cannot say more without details on how you compile the application and how you run the experiment.

> analyzer query aggregated.json -o whitelist.txt
> gives me an empty whitelist for openssl meaning that none of the conditional jumps are safe. Is that normal?

No, it's not. See above.

**Comment by OleksiiOleksenko** [comment] 2020-12-26 16:15
Closing because the questions are not related to the original issue. If you have more questions, please, open a separate issue. The answers should be searchable.

**Closed as completed by OleksiiOleksenko** 2020-12-26 16:15 UTC
